name: stellite
version: 0.11.1.0-1
summary: "Stellite : Global Wealth Distribution www.stellite.cash"
description: |
    Stellite inherits privacy features of Monero. It's also designed to be mobile friendly and aim to globally distribute wealth
grade: devel
confinement: strict

apps:
    stellited:
        daemon: forking
        command: |
          stellited-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/stellited.conf
        plugs:
            - network
            - network-bind
    stellite-wallet-rpc:
        command: |
          stellite-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    stellite-wallet-cli:
        command: |
          stellite-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/stellited.conf: etc/stellited.conf
            contrib/snap/stellited-wrapper: bin/stellited-wrapper
        prime:
            - etc
            - bin
